osm16_birthday:
  id: osm_16
  alt: Celebrate the 16th OSM anniversary
  link: https://wiki.openstreetmap.org/wiki/OpenStreetMap_16th_Anniversary_Birthday_party
  img: banners/osm16_birthday.png
  enddate: 2020-aug-10
